### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by chenqq1** [xhpxiaohaipeng/An-Improved-LSTM-Model-for--Behavior-Recognition-of-Intelligent-Vehicles#2]
train_states.txt里面的数据是什么含义？

**Comment by xhpxiaohaipeng** [comment]
里面有数据，可以去运行代码看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [xhpxiaohaipeng/An-Improved-LSTM-Model-for--Behavior-Recognition-of-Intelligent-Vehicles] 关于数据集 (Issue #2)




 
Closed #2 as completed.
